extension ProxyPropertyGenerator {
    static func loadIconNames() -> [String] {
        var iconNames = [String]()
        iconNames.append("Acorn")
        iconNames.append("Aquarium")
        iconNames.append("Armored Helmet")
        iconNames.append("Astronaut Helmet")
        iconNames.append("Astronaut")
        iconNames.append("Avocado")
        iconNames.append("Baby Bottle")
        iconNames.append("Baby")
        iconNames.append("Balloon")
        iconNames.append("Banana Split")
        iconNames.append("Banana")
        iconNames.append("Bat")
        iconNames.append("Beach Ball")
        iconNames.append("Bee Hive")
        iconNames.append("Beer")
        iconNames.append("Black Cat")
        iconNames.append("Broccoli")
        iconNames.append("Butterfly")
        iconNames.append("Cactus")
        iconNames.append("Carrot")
        iconNames.append("Cheese")
        iconNames.append("Cherry")
        iconNames.append("Chicken")
        iconNames.append("Chinese Peach")
        iconNames.append("Chips")
        iconNames.append("Chocolate Bar")
        iconNames.append("Cinnamon Roll")
        iconNames.append("Clover")
        iconNames.append("Coconut Cocktail")
        iconNames.append("Coconut")
        iconNames.append("Coffee Pot")
        iconNames.append("Coins")
        iconNames.append("Comet")
        iconNames.append("Cookies")
        iconNames.append("Corgi")
        iconNames.append("Corn")
        iconNames.append("Crab")
        iconNames.append("Crying Face")
        iconNames.append("Crystal Ball")
        iconNames.append("Crystal")
        iconNames.append("Cupcake")
        iconNames.append("Diamond")
        iconNames.append("Dog Bone")
        iconNames.append("Dog With Ball")
        iconNames.append("Dog")
        iconNames.append("Dolphin")
        iconNames.append("Donut")
        iconNames.append("Duck")
        iconNames.append("Earth")
        iconNames.append("Eggplant")
        iconNames.append("Einstein")
        iconNames.append("Elephant")
        iconNames.append("Falcon")
        iconNames.append("Finish Flag")
        iconNames.append("Fish")
        iconNames.append("Flame")
        iconNames.append("Football")
        iconNames.append("Fox")
        iconNames.append("French Fries")
        iconNames.append("Frog")
        iconNames.append("Genie Lamp")
        iconNames.append("Ghost")
        iconNames.append("Gold Bars")
        iconNames.append("Gorilla")
        iconNames.append("Grapes")
        iconNames.append("Hamburger")
        iconNames.append("Happy Face")
        iconNames.append("Heart Balloon")
        iconNames.append("Horse")
        iconNames.append("Hotdog")
        iconNames.append("Hummingbird")
        iconNames.append("Ice Cream")
        iconNames.append("Innocent Face")
        iconNames.append("Jack O Lantern")
        iconNames.append("Kangaroo")
        iconNames.append("Kissing Face")
        iconNames.append("Kiwi Bird")
        iconNames.append("Kiwi")
        iconNames.append("Koi Fish")
        iconNames.append("Laughing Face")
        iconNames.append("Lotus")
        iconNames.append("Maneki")
        iconNames.append("Mario")
        iconNames.append("Milkshake")
        iconNames.append("Minecraft Sword")
        iconNames.append("Monarch Butterfly")
        iconNames.append("Money Bag")
        iconNames.append("Money")
        iconNames.append("Moon")
        iconNames.append("Ninja")
        iconNames.append("Noodles")
        iconNames.append("Pancakes")
        iconNames.append("Panda")
        iconNames.append("Peacock")
        iconNames.append("Penguin")
        iconNames.append("Pig")
        iconNames.append("Pikachu")
        iconNames.append("Pineapple")
        iconNames.append("Ping Pong")
        iconNames.append("Pink Cupcake")
        iconNames.append("Pizza")
        iconNames.append("Plushie")
        iconNames.append("Pokeball")
        iconNames.append("Pot Of Gold")
        iconNames.append("Present")
        iconNames.append("Puffin")
        iconNames.append("Puzzled Face")
        iconNames.append("Rabbit")
        iconNames.append("Rainbow")
        iconNames.append("Rhino")
        iconNames.append("Rice")
        iconNames.append("Robot")
        iconNames.append("Ruby")
        iconNames.append("Sailing Ship")
        iconNames.append("Samurai Helmet")
        iconNames.append("Saturn")
        iconNames.append("Seahorse")
        iconNames.append("Sheep")
        iconNames.append("Shiba Inu")
        iconNames.append("Shield")
        iconNames.append("Silver Ring")
        iconNames.append("Skateboard")
        iconNames.append("Smiling Face With Heart")
        iconNames.append("Snorlax")
        iconNames.append("Snowman")
        iconNames.append("Space Fighter")
        iconNames.append("Starfish")
        iconNames.append("Stork")
        iconNames.append("Strawberry")
        iconNames.append("Sun")
        iconNames.append("Sword")
        iconNames.append("Taco")
        iconNames.append("Tennis")
        iconNames.append("Toaster")
        iconNames.append("Tomato")
        iconNames.append("Treasure Chest")
        iconNames.append("Triforce")
        iconNames.append("Turtle")
        iconNames.append("Unicorn")
        iconNames.append("Werewolf")
        iconNames.append("Whale")
        iconNames.append("Winking Face")
        iconNames.append("Wizard Hat")
        iconNames.append("Yellow Bird")
        iconNames.append("Zebra")
        return iconNames
    }
}
