extension ProxyPropertyGenerator {
    static func loadIconNames() -> [String] {
        var iconNames = [String]()
        iconNames.append("Acorn")
        iconNames.append("Anubis")
        iconNames.append("Aquarium")
        iconNames.append("Astronaut Helmet")
        iconNames.append("Astronaut")
        iconNames.append("Avocado")
        iconNames.append("Baby Bottle")
        iconNames.append("Baby")
        iconNames.append("Balloon")
        iconNames.append("Banana Split")
        iconNames.append("Banana")
        iconNames.append("Basketball")
        iconNames.append("Bat")
        iconNames.append("Beach Ball")
        iconNames.append("Bee")
        iconNames.append("Bee Hive")
        iconNames.append("Beer")
        iconNames.append("Black Cat")
        iconNames.append("Blue Butterfly")
        iconNames.append("Bowling")
        iconNames.append("Broccoli")
        iconNames.append("Bronze Bars")
        iconNames.append("Cactus")
        iconNames.append("Carrot")
        iconNames.append("Cheese")
        iconNames.append("Cherry")
        iconNames.append("Chess Knight")
        iconNames.append("Chicken")
        iconNames.append("Chinese Peach")
        iconNames.append("Chips")
        iconNames.append("Chocolate Bar")
        iconNames.append("Cinnamon Roll")
        iconNames.append("Clover")
        iconNames.append("Coconut Cocktail")
        iconNames.append("Coconut")
        iconNames.append("Coffee Pot")
        iconNames.append("Coins")
        iconNames.append("Comet")
        iconNames.append("Confused Face")
        iconNames.append("Cookies")
        iconNames.append("Corgi")
        iconNames.append("Corn")
        iconNames.append("Crab")
        iconNames.append("Crown")
        iconNames.append("Crying Face")
        iconNames.append("Crystal Ball")
        iconNames.append("Crystal")
        iconNames.append("Cupcake")
        iconNames.append("Diamond")
        iconNames.append("Dog Bone")
        iconNames.append("Dog With Ball")
        iconNames.append("Dog")
        iconNames.append("Dolphin")
        iconNames.append("Donut")
        iconNames.append("Dove")
        iconNames.append("Duck")
        iconNames.append("Earth")
        iconNames.append("Eggplant")
        iconNames.append("Einstein")
        iconNames.append("Elephant")
        iconNames.append("Falcon")
        iconNames.append("Finish Flag")
        iconNames.append("Fish")
        iconNames.append("Flame")
        iconNames.append("Float")
        iconNames.append("Football")
        iconNames.append("Fox")
        iconNames.append("French Fries")
        iconNames.append("Frog")
        iconNames.append("Genie Lamp")
        iconNames.append("Ghost")
        iconNames.append("Gold Bars")
        iconNames.append("Gold Crown")
        iconNames.append("Gorilla")
        iconNames.append("Grapes")
        iconNames.append("Guitar")
        iconNames.append("Hamburger")
        iconNames.append("Happy Face")
        iconNames.append("Heart")
        iconNames.append("Heart Balloon")
        iconNames.append("Honey")
        iconNames.append("Horse")
        iconNames.append("Hotdog")
        iconNames.append("Humming bird")
        iconNames.append("Ice Cream")
        iconNames.append("Innocent Face")
        iconNames.append("Jack O Lantern")
        iconNames.append("Katana")
        iconNames.append("Kangaroo")
        iconNames.append("Keg")
        iconNames.append("Kissing Face")
        iconNames.append("Kiwi Bird")
        iconNames.append("Kiwi")
        iconNames.append("Koi Fish")
        iconNames.append("Laughing Face")
        iconNames.append("Lotus")
        iconNames.append("Maneki")
        iconNames.append("Milkshake")
        iconNames.append("Money Bag")
        iconNames.append("Money")
        iconNames.append("Moon")
        iconNames.append("Motorbike Helmet")
        iconNames.append("Mushroom")
        iconNames.append("Ninja")
        iconNames.append("Noodles")
        iconNames.append("Orange Butterfly")
        iconNames.append("Pancakes")
        iconNames.append("Panda")
        iconNames.append("Parrot")
        iconNames.append("Peacock")
        iconNames.append("Penguin")
        iconNames.append("Phoenix")
        iconNames.append("Piano")
        iconNames.append("Pig")
        iconNames.append("Piggy Bank")
        iconNames.append("Pineapple")
        iconNames.append("Ping Pong")
        iconNames.append("Pink Cupcake")
        iconNames.append("Pizza")
        iconNames.append("Plushie")
        iconNames.append("Pot Of Gold")
        iconNames.append("Present")
        iconNames.append("Puffin")
        iconNames.append("Rabbit")
        iconNames.append("Rainbow")
        iconNames.append("Rhino")
        iconNames.append("Rice")
        iconNames.append("Robot")
        iconNames.append("Roman Helmet")
        iconNames.append("Ruby")
        iconNames.append("Sailing Ship")
        iconNames.append("Samurai Helmet")
        iconNames.append("Saturn")
        iconNames.append("Seahorse")
        iconNames.append("Sheep")
        iconNames.append("Shiba Inu")
        iconNames.append("Shield")
        iconNames.append("Shrimp")
        iconNames.append("Silver Bars")
        iconNames.append("Silver Ring")
        iconNames.append("Skate board")
        iconNames.append("Slime")
        iconNames.append("Smiling Face With Heart")
        iconNames.append("Snowman")
        iconNames.append("Space Fighter")
        iconNames.append("Space Shuttle")
        iconNames.append("Spartan Helmet")
        iconNames.append("Starfish")
        iconNames.append("Stork")
        iconNames.append("Strawberry")
        iconNames.append("Sun")
        iconNames.append("Swan")
        iconNames.append("Sword")
        iconNames.append("Taco")
        iconNames.append("Tennis")
        iconNames.append("Toaster")
        iconNames.append("Tomato")
        iconNames.append("Treasure Chest")
        iconNames.append("Turtle")
        iconNames.append("UFO")
        iconNames.append("Unicorn")
        iconNames.append("Virus")
        iconNames.append("Werewolf")
        iconNames.append("Whale")
        iconNames.append("Winking Face")
        iconNames.append("Wizard Hat")
        iconNames.append("Yellow Bird")
        iconNames.append("Zebra")
        return iconNames
    }
}
