disabled_rules:
  - line_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - function_body_length
  - weak_delegate
  - identifier_name
  - compiler_protocol_init
  - file_length
  - xctfail_message

excluded:
  - Pods

type_name:
  min_length: 2