disabled_rules:
  - compiler_protocol_init
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - line_length
  - multiple_closures_with_trailing_closure
  - weak_delegate
  - xctfail_message

excluded:
  - Pods

identifier_name:
  min_length: 1

type_name:
  min_length: 2