extension ProxyService {
    static func makeIconNames() -> [String] {
        var iconNames = [String]()
        iconNames.append("Acorn")
        iconNames.append("Aquarium")
        iconNames.append("Armored Helmet")
        iconNames.append("Astronaut Helmet")
        iconNames.append("Astronaut")
        iconNames.append("Baby Bottle")
        iconNames.append("Baby")
        iconNames.append("Balloon")
        iconNames.append("Banana Split")
        iconNames.append("Banana")
        iconNames.append("Beach Ball")
        iconNames.append("Bee Hive")
        iconNames.append("Beer")
        iconNames.append("Black Cat")
        iconNames.append("Broccoli")
        iconNames.append("Cactus")
        iconNames.append("Carrot")
        iconNames.append("Cheese")
        iconNames.append("Cherry")
        iconNames.append("Chicken")
        iconNames.append("Cinnamon Roll")
        iconNames.append("Clover")
        iconNames.append("Coconut Cocktail")
        iconNames.append("Coffee Pot")
        iconNames.append("Coins")
        iconNames.append("Comet")
        iconNames.append("Cookies")
        iconNames.append("Corgi")
        iconNames.append("Corn")
        iconNames.append("Crab")
        iconNames.append("Crystal Ball")
        iconNames.append("Crystal")
        iconNames.append("Cupcake")
        iconNames.append("Dog Bone")
        iconNames.append("Dog With Ball")
        iconNames.append("Dog")
        iconNames.append("Dolphin")
        iconNames.append("Donut")
        iconNames.append("Duck")
        iconNames.append("Eggplant")
        iconNames.append("Einstein")
        iconNames.append("Elephant")
        iconNames.append("Falcon")
        iconNames.append("Finish Flag")
        iconNames.append("Fish")
        iconNames.append("Flame")
        iconNames.append("Football")
        iconNames.append("French Fries")
        iconNames.append("Frog")
        iconNames.append("Gorilla")
        iconNames.append("Grapes")
        iconNames.append("Hamburger")
        iconNames.append("Heart Balloon")
        iconNames.append("Horse")
        iconNames.append("Hotdog")
        iconNames.append("Hummingbird")
        iconNames.append("Ice Cream")
        iconNames.append("Kangaroo")
        iconNames.append("Kiwi Bird")
        iconNames.append("Kiwi")
        iconNames.append("Minecraft Sword")
        iconNames.append("Money Bag")
        iconNames.append("Money")
        iconNames.append("Moon")
        iconNames.append("Noodles")
        iconNames.append("Pancakes")
        iconNames.append("Panda")
        iconNames.append("Pig")
        iconNames.append("Pikachu")
        iconNames.append("Ping Pong")
        iconNames.append("Pink Cupcake")
        iconNames.append("Pizza")
        iconNames.append("Plushie")
        iconNames.append("Pokeball")
        iconNames.append("Pot Of Gold")
        iconNames.append("Present")
        iconNames.append("Puffin")
        iconNames.append("Rabbit")
        iconNames.append("Rainbow")
        iconNames.append("Rhino")
        iconNames.append("Rice")
        iconNames.append("Saturn")
        iconNames.append("Seahorse")
        iconNames.append("Sheep")
        iconNames.append("Skateboard")
        iconNames.append("Space Fighter")
        iconNames.append("Starfish")
        iconNames.append("Stork")
        iconNames.append("Strawberry")
        iconNames.append("Sun")
        iconNames.append("Sword")
        iconNames.append("Taco")
        iconNames.append("Tennis")
        iconNames.append("Tomato")
        iconNames.append("Treasure Chest")
        iconNames.append("Triforce")
        iconNames.append("Turtle")
        iconNames.append("Unicorn")
        iconNames.append("Whale")
        iconNames.append("Wizard Hat")
        iconNames.append("Yellow Bird")
        return iconNames
    }
}
