extension Shared {
    func loadProxyIconNames() {
        proxyIconNames.append("Acorn")
        proxyIconNames.append("Aquarium")
        proxyIconNames.append("Armored Helmet")
        proxyIconNames.append("Astronaut Helmet")
        proxyIconNames.append("Astronaut")
        proxyIconNames.append("Baby Bottle")
        proxyIconNames.append("Baby")
        proxyIconNames.append("Balloon")
        proxyIconNames.append("Banana Split")
        proxyIconNames.append("Banana")
        proxyIconNames.append("Beach Ball")
        proxyIconNames.append("Bee Hive")
        proxyIconNames.append("Beer")
        proxyIconNames.append("Black Cat")
        proxyIconNames.append("Broccoli")
        proxyIconNames.append("Cactus")
        proxyIconNames.append("Carrot")
        proxyIconNames.append("Cheese")
        proxyIconNames.append("Cherry")
        proxyIconNames.append("Chicken")
        proxyIconNames.append("Cinnamon Roll")
        proxyIconNames.append("Clover")
        proxyIconNames.append("Coconut Cocktail")
        proxyIconNames.append("Coffee Pot")
        proxyIconNames.append("Coins")
        proxyIconNames.append("Comet")
        proxyIconNames.append("Cookies")
        proxyIconNames.append("Corgi")
        proxyIconNames.append("Corn")
        proxyIconNames.append("Crab")
        proxyIconNames.append("Crystal Ball")
        proxyIconNames.append("Crystal")
        proxyIconNames.append("Cupcake")
        proxyIconNames.append("Dog Bone")
        proxyIconNames.append("Dog With Ball")
        proxyIconNames.append("Dog")
        proxyIconNames.append("Dolphin")
        proxyIconNames.append("Donut")
        proxyIconNames.append("Duck")
        proxyIconNames.append("Eggplant")
        proxyIconNames.append("Einstein")
        proxyIconNames.append("Elephant")
        proxyIconNames.append("Falcon")
        proxyIconNames.append("Finish Flag")
        proxyIconNames.append("Fish")
        proxyIconNames.append("Flame")
        proxyIconNames.append("Football")
        proxyIconNames.append("French Fries")
        proxyIconNames.append("Frog")
        proxyIconNames.append("Gorilla")
        proxyIconNames.append("Grapes")
        proxyIconNames.append("Hamburger")
        proxyIconNames.append("Heart Balloon")
        proxyIconNames.append("Horse")
        proxyIconNames.append("Hotdog")
        proxyIconNames.append("Hummingbird")
        proxyIconNames.append("Ice Cream")
        proxyIconNames.append("Kangaroo")
        proxyIconNames.append("Kiwi Bird")
        proxyIconNames.append("Kiwi")
        proxyIconNames.append("Minecraft Sword")
        proxyIconNames.append("Money Bag")
        proxyIconNames.append("Money")
        proxyIconNames.append("Moon")
        proxyIconNames.append("Noodles")
        proxyIconNames.append("Pancakes")
        proxyIconNames.append("Panda")
        proxyIconNames.append("Pig")
        proxyIconNames.append("Pikachu")
        proxyIconNames.append("Ping Pong")
        proxyIconNames.append("Pink Cupcake")
        proxyIconNames.append("Pizza")
        proxyIconNames.append("Plushie")
        proxyIconNames.append("Pokeball")
        proxyIconNames.append("Pot Of Gold")
        proxyIconNames.append("Present")
        proxyIconNames.append("Puffin")
        proxyIconNames.append("Rabbit")
        proxyIconNames.append("Rainbow")
        proxyIconNames.append("Rhino")
        proxyIconNames.append("Rice")
        proxyIconNames.append("Saturn")
        proxyIconNames.append("Seahorse")
        proxyIconNames.append("Sheep")
        proxyIconNames.append("Skateboard")
        proxyIconNames.append("Space Fighter")
        proxyIconNames.append("Starfish")
        proxyIconNames.append("Stork")
        proxyIconNames.append("Strawberry")
        proxyIconNames.append("Sun")
        proxyIconNames.append("Sword")
        proxyIconNames.append("Taco")
        proxyIconNames.append("Tennis")
        proxyIconNames.append("Tomato")
        proxyIconNames.append("Treasure Chest")
        proxyIconNames.append("Triforce")
        proxyIconNames.append("Turtle")
        proxyIconNames.append("Unicorn")
        proxyIconNames.append("Whale")
        proxyIconNames.append("Wizard Hat")
        proxyIconNames.append("Yellow Bird")
    }
}
