//
//  DefaultIcons.swift
//  proxy
//
//  Created by Quan Vo on 9/9/16.
//  Copyright © 2016 Quan Vo. All rights reserved.
//

struct DefaultIcons {
    
    let defaultIcons: Any
    
    init(id: String) {
        let timestamp = NSDate().timeIntervalSince1970
        defaultIcons = [
            "/icons/\(id)/Aquarium-96": ["name": "Aquarium-96", "timestamp": timestamp],
            "/icons/\(id)/Armored Helmet-96": ["name": "Armored Helmet-96", "timestamp": timestamp],
            "/icons/\(id)/Astronaut Helmet-96": ["name": "Astronaut Helmet-96", "timestamp": timestamp],
            "/icons/\(id)/Astronaut-96": ["name": "Astronaut-96", "timestamp": timestamp],
            "/icons/\(id)/Baby Bottle-96": ["name": "Baby Bottle-96", "timestamp": timestamp],
            "/icons/\(id)/Babys Room-96": ["name": "Babys Room-96", "timestamp": timestamp],
            "/icons/\(id)/Banana Split-96": ["name": "Banana Split-96", "timestamp": timestamp],
            "/icons/\(id)/Banana-96": ["name": "Banana-96", "timestamp": timestamp],
            "/icons/\(id)/Banknotes-96": ["name": "Banknotes-96", "timestamp": timestamp],
            "/icons/\(id)/Beach Ball-96": ["name": "Beach Ball-96", "timestamp": timestamp],
            "/icons/\(id)/Beer-96": ["name": "Beer-96", "timestamp": timestamp],
            "/icons/\(id)/Bird-96": ["name": "Bird-96", "timestamp": timestamp],
            "/icons/\(id)/Broccoli-96": ["name": "Broccoli-96", "timestamp": timestamp],
            "/icons/\(id)/Carrot-96": ["name": "Carrot-96", "timestamp": timestamp],
            "/icons/\(id)/Cat-96": ["name": "Cat-96", "timestamp": timestamp],
            "/icons/\(id)/Cheese-96": ["name": "Cheese-96", "timestamp": timestamp],
            "/icons/\(id)/Cherry-96": ["name": "Cherry-96", "timestamp": timestamp],
            "/icons/\(id)/Chicken-96": ["name": "Chicken-96", "timestamp": timestamp],
            "/icons/\(id)/Cinnamon Roll-96": ["name": "Cinnamon Roll-96", "timestamp": timestamp],
            "/icons/\(id)/Clover-96": ["name": "Clover-96", "timestamp": timestamp],
            "/icons/\(id)/Coconut Cocktail-96": ["name": "Coconut Cocktail-96", "timestamp": timestamp],
            "/icons/\(id)/Coffee Pot-96": ["name": "Coffee Pot-96", "timestamp": timestamp],
            "/icons/\(id)/Coins-96": ["name": "Coins-96", "timestamp": timestamp],
            "/icons/\(id)/Comet-96": ["name": "Comet-96", "timestamp": timestamp],
            "/icons/\(id)/Confectionery-96": ["name": "Confectionery-96", "timestamp": timestamp],
            "/icons/\(id)/Cookies-96": ["name": "Cookies-96", "timestamp": timestamp],
            "/icons/\(id)/Corgi-96": ["name": "Corgi-96", "timestamp": timestamp],
            "/icons/\(id)/Corn-96": ["name": "Corn-96", "timestamp": timestamp],
            "/icons/\(id)/Crab-96": ["name": "Crab-96", "timestamp": timestamp],
            "/icons/\(id)/Crystal Ball-96": ["name": "Crystal Ball-96", "timestamp": timestamp],
            "/icons/\(id)/Crystal-96": ["name": "Crystal-96", "timestamp": timestamp],
            "/icons/\(id)/Cupcake-96": ["name": "Cupcake-96", "timestamp": timestamp],
            "/icons/\(id)/Dog Bone-96": ["name": "Dog Bone-96", "timestamp": timestamp],
            "/icons/\(id)/Dog Park-96": ["name": "Dog Park-96", "timestamp": timestamp],
            "/icons/\(id)/Dog-96": ["name": "Dog-96", "timestamp": timestamp],
            "/icons/\(id)/Dolphin-96": ["name": "Dolphin-96", "timestamp": timestamp],
            "/icons/\(id)/Doughnut-96": ["name": "Doughnut-96", "timestamp": timestamp],
            "/icons/\(id)/Duck-96": ["name": "Duck-96", "timestamp": timestamp],
            "/icons/\(id)/Eggplant-96": ["name": "Eggplant-96", "timestamp": timestamp],
            "/icons/\(id)/Einstein-96": ["name": "Einstein-96", "timestamp": timestamp],
            "/icons/\(id)/Elephant-96": ["name": "Elephant-96", "timestamp": timestamp],
            "/icons/\(id)/Falcon-96": ["name": "Falcon-96", "timestamp": timestamp],
            "/icons/\(id)/Finish Flag-96": ["name": "Finish Flag-96", "timestamp": timestamp],
            "/icons/\(id)/Fire Element-96": ["name": "Fire Element-96", "timestamp": timestamp],
            "/icons/\(id)/Fish Food-96": ["name": "Fish Food-96", "timestamp": timestamp],
            "/icons/\(id)/Flying Stork With Bundle-96": ["name": "Flying Stork With Bundle-96", "timestamp": timestamp],
            "/icons/\(id)/French Fries-96": ["name": "French Fries-96", "timestamp": timestamp],
            "/icons/\(id)/Frog-96": ["name": "Frog-96", "timestamp": timestamp],
            "/icons/\(id)/Gift-96": ["name": "Gift-96", "timestamp": timestamp],
            "/icons/\(id)/Gold Pot-96": ["name": "Gold Pot-96", "timestamp": timestamp],
            "/icons/\(id)/Gorilla-96": ["name": "Gorilla-96", "timestamp": timestamp],
            "/icons/\(id)/Grapes-96": ["name": "Grapes-96", "timestamp": timestamp],
            "/icons/\(id)/Hamburger-96": ["name": "Hamburger-96", "timestamp": timestamp],
            "/icons/\(id)/Heart Balloon-96": ["name": "Heart Balloon-96", "timestamp": timestamp],
            "/icons/\(id)/Hornet Hive-96": ["name": "Hornet Hive-96", "timestamp": timestamp],
            "/icons/\(id)/Horse-96": ["name": "Horse-96", "timestamp": timestamp],
            "/icons/\(id)/Hot Dog-96": ["name": "Hot Dog-96", "timestamp": timestamp],
            "/icons/\(id)/Hummingbird-96": ["name": "Hummingbird-96", "timestamp": timestamp],
            "/icons/\(id)/Ice Cream Cone-96": ["name": "Ice Cream Cone-96", "timestamp": timestamp],
            "/icons/\(id)/Kangaroo-96": ["name": "Kangaroo-96", "timestamp": timestamp],
            "/icons/\(id)/Kiwi Bird-96": ["name": "Kiwi Bird-96", "timestamp": timestamp],
            "/icons/\(id)/Kiwi-96": ["name": "Kiwi-96", "timestamp": timestamp],
            "/icons/\(id)/Minecraft Sword-96": ["name": "Minecraft Sword-96", "timestamp": timestamp],
            "/icons/\(id)/Money Bag-96": ["name": "Money Bag-96", "timestamp": timestamp],
            "/icons/\(id)/Moon-96": ["name": "Moon-96", "timestamp": timestamp],
            "/icons/\(id)/Noodles-96": ["name": "Noodles-96", "timestamp": timestamp],
            "/icons/\(id)/Nut-96": ["name": "Nut-96", "timestamp": timestamp],
            "/icons/\(id)/Pancake-96": ["name": "Pancake-96", "timestamp": timestamp],
            "/icons/\(id)/Panda-96": ["name": "Panda-96", "timestamp": timestamp],
            "/icons/\(id)/Party Baloon-96": ["name": "Party Baloon-96", "timestamp": timestamp],
            "/icons/\(id)/Pig-96": ["name": "Pig-96", "timestamp": timestamp],
            "/icons/\(id)/Ping Pong-96": ["name": "Ping Pong-96", "timestamp": timestamp],
            "/icons/\(id)/Pizza-96": ["name": "Pizza-96", "timestamp": timestamp],
            "/icons/\(id)/Planet-96": ["name": "Planet-96", "timestamp": timestamp],
            "/icons/\(id)/Plush-96": ["name": "Plush-96", "timestamp": timestamp],
            "/icons/\(id)/Pokeball-96": ["name": "Pokeball-96", "timestamp": timestamp],
            "/icons/\(id)/Pokemon-96": ["name": "Pokemon-96", "timestamp": timestamp],
            "/icons/\(id)/Puffin Bird-96": ["name": "Puffin Bird-96", "timestamp": timestamp],
            "/icons/\(id)/Rabbit-96": ["name": "Rabbit-96", "timestamp": timestamp],
            "/icons/\(id)/Rainbow-96": ["name": "Rainbow-96", "timestamp": timestamp],
            "/icons/\(id)/Rhinoceros-96": ["name": "Rhinoceros-96", "timestamp": timestamp],
            "/icons/\(id)/Rice Bowl-96": ["name": "Rice Bowl-96", "timestamp": timestamp],
            "/icons/\(id)/Seahorse-96": ["name": "Seahorse-96", "timestamp": timestamp],
            "/icons/\(id)/Sheep-96": ["name": "Sheep-96", "timestamp": timestamp],
            "/icons/\(id)/Skateboard-96": ["name": "Skateboard-96", "timestamp": timestamp],
            "/icons/\(id)/Space Fighter-96": ["name": "Space Fighter-96", "timestamp": timestamp],
            "/icons/\(id)/Sport-96": ["name": "Sport-96", "timestamp": timestamp],
            "/icons/\(id)/Starfish-96": ["name": "Starfish-96", "timestamp": timestamp],
            "/icons/\(id)/Strawberry-96": ["name": "Strawberry-96", "timestamp": timestamp],
            "/icons/\(id)/Summer-96": ["name": "Summer-96", "timestamp": timestamp],
            "/icons/\(id)/Sword-96": ["name": "Sword-96", "timestamp": timestamp],
            "/icons/\(id)/Taco-96": ["name": "Taco-96", "timestamp": timestamp],
            "/icons/\(id)/Tennis-96": ["name": "Tennis-96", "timestamp": timestamp],
            "/icons/\(id)/Tomato-96": ["name": "Tomato-96", "timestamp": timestamp],
            "/icons/\(id)/Treasure Chest-96": ["name": "Treasure Chest-96", "timestamp": timestamp],
            "/icons/\(id)/Triforce-96": ["name": "Triforce-96", "timestamp": timestamp],
            "/icons/\(id)/Turtle-96": ["name": "Turtle-96", "timestamp": timestamp],
            "/icons/\(id)/Unicorn-96": ["name": "Unicorn-96", "timestamp": timestamp],
            "/icons/\(id)/Western-96": ["name": "Western-96", "timestamp": timestamp],
            "/icons/\(id)/Whale-96": ["name": "Whale-96", "timestamp": timestamp],
            "/icons/\(id)/Wizard-96": ["name": "Wizard-96", "timestamp": timestamp]
        ]
    }
}
