//
//  DefaultIcons.swift
//  proxy
//
//  Created by Quan Vo on 9/9/16.
//  Copyright © 2016 Quan Vo. All rights reserved.
//

struct DefaultIcons {
    
    let defaultIcons: AnyObject
    
    init(id: String) {
        let timestamp = NSDate().timeIntervalSince1970
        defaultIcons = [
            "/icons/\(id)/Aquarium-96": timestamp,
            "/icons/\(id)/Armored Helmet-96": timestamp,
            "/icons/\(id)/Astronaut Helmet-96": timestamp,
            "/icons/\(id)/Astronaut-96": timestamp,
            "/icons/\(id)/Baby Bottle-96": timestamp,
            "/icons/\(id)/Babys Room-96": timestamp,
            "/icons/\(id)/Banana Split-96": timestamp,
            "/icons/\(id)/Banana-96": timestamp,
            "/icons/\(id)/Banknotes-96": timestamp,
            "/icons/\(id)/Beach Ball-96": timestamp,
            "/icons/\(id)/Beer-96": timestamp,
            "/icons/\(id)/Bird-96": timestamp,
            "/icons/\(id)/Broccoli-96": timestamp,
            "/icons/\(id)/Carrot-96": timestamp,
            "/icons/\(id)/Cat-96": timestamp,
            "/icons/\(id)/Cheese-96": timestamp,
            "/icons/\(id)/Cherry-96": timestamp,
            "/icons/\(id)/Chicken-96": timestamp,
            "/icons/\(id)/Cinnamon Roll-96": timestamp,
            "/icons/\(id)/Clover-96": timestamp,
            "/icons/\(id)/Coconut Cocktail-96": timestamp,
            "/icons/\(id)/Coffee Pot-96": timestamp,
            "/icons/\(id)/Coins-96": timestamp,
            "/icons/\(id)/Comet-96": timestamp,
            "/icons/\(id)/Confectionery-96": timestamp,
            "/icons/\(id)/Cookies-96": timestamp,
            "/icons/\(id)/Corgi-96": timestamp,
            "/icons/\(id)/Corn-96": timestamp,
            "/icons/\(id)/Crab-96": timestamp,
            "/icons/\(id)/Crystal Ball-96": timestamp,
            "/icons/\(id)/Crystal-96": timestamp,
            "/icons/\(id)/Cupcake-96": timestamp,
            "/icons/\(id)/Dog Bone-96": timestamp,
            "/icons/\(id)/Dog Park-96": timestamp,
            "/icons/\(id)/Dog-96": timestamp,
            "/icons/\(id)/Dolphin-96": timestamp,
            "/icons/\(id)/Doughnut-96": timestamp,
            "/icons/\(id)/Duck-96": timestamp,
            "/icons/\(id)/Eggplant-96": timestamp,
            "/icons/\(id)/Einstein-96": timestamp,
            "/icons/\(id)/Elephant-96": timestamp,
            "/icons/\(id)/Falcon-96": timestamp,
            "/icons/\(id)/Finish Flag-96": timestamp,
            "/icons/\(id)/Fire Element-96": timestamp,
            "/icons/\(id)/Fish Food-96": timestamp,
            "/icons/\(id)/Flying Stork With Bundle-96": timestamp,
            "/icons/\(id)/French Fries-96": timestamp,
            "/icons/\(id)/Frog-96": timestamp,
            "/icons/\(id)/Gift-96": timestamp,
            "/icons/\(id)/Gold Pot-96": timestamp,
            "/icons/\(id)/Gorilla-96": timestamp,
            "/icons/\(id)/Grapes-96": timestamp,
            "/icons/\(id)/Hamburger-96": timestamp,
            "/icons/\(id)/Heart Balloon-96": timestamp,
            "/icons/\(id)/Hornet Hive-96": timestamp,
            "/icons/\(id)/Horse-96": timestamp,
            "/icons/\(id)/Hot Dog-96": timestamp,
            "/icons/\(id)/Hummingbird-96": timestamp,
            "/icons/\(id)/Ice Cream Cone-96": timestamp,
            "/icons/\(id)/Kangaroo-96": timestamp,
            "/icons/\(id)/Kiwi Bird-96": timestamp,
            "/icons/\(id)/Kiwi-96": timestamp,
            "/icons/\(id)/Minecraft Sword-96": timestamp,
            "/icons/\(id)/Money Bag-96": timestamp,
            "/icons/\(id)/Moon-96": timestamp,
            "/icons/\(id)/Noodles-96": timestamp,
            "/icons/\(id)/Nut-96": timestamp,
            "/icons/\(id)/Pancake-96": timestamp,
            "/icons/\(id)/Panda-96": timestamp,
            "/icons/\(id)/Party Baloon-96": timestamp,
            "/icons/\(id)/Pig-96": timestamp,
            "/icons/\(id)/Ping Pong-96": timestamp,
            "/icons/\(id)/Pizza-96": timestamp,
            "/icons/\(id)/Planet-96": timestamp,
            "/icons/\(id)/Plush-96": timestamp,
            "/icons/\(id)/Pokeball-96": timestamp,
            "/icons/\(id)/Pokemon-96": timestamp,
            "/icons/\(id)/Puffin Bird-96": timestamp,
            "/icons/\(id)/Rabbit-96": timestamp,
            "/icons/\(id)/Rainbow-96": timestamp,
            "/icons/\(id)/Rhinoceros-96": timestamp,
            "/icons/\(id)/Rice Bowl-96": timestamp,
            "/icons/\(id)/Seahorse-96": timestamp,
            "/icons/\(id)/Sheep-96": timestamp,
            "/icons/\(id)/Skateboard-96": timestamp,
            "/icons/\(id)/Space Fighter-96": timestamp,
            "/icons/\(id)/Sport-96": timestamp,
            "/icons/\(id)/Starfish-96": timestamp,
            "/icons/\(id)/Strawberry-96": timestamp,
            "/icons/\(id)/Summer-96": timestamp,
            "/icons/\(id)/Sword-96": timestamp,
            "/icons/\(id)/Taco-96": timestamp,
            "/icons/\(id)/Tennis-96": timestamp,
            "/icons/\(id)/Tomato-96": timestamp,
            "/icons/\(id)/Treasure Chest-96": timestamp,
            "/icons/\(id)/Triforce-96": timestamp,
            "/icons/\(id)/Turtle-96": timestamp,
            "/icons/\(id)/Unicorn-96": timestamp,
            "/icons/\(id)/Western-96": timestamp,
            "/icons/\(id)/Whale-96": timestamp,
            "/icons/\(id)/Wizard-96": timestamp]
    }
}